# Generated by Django 3.1.6 on 2021-03-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210320_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.CharField(default='solution !', max_length=1000),
        ),
    ]
