# Generated by Django 3.1.6 on 2021-05-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20210522_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='final_sub',
            field=models.BooleanField(default=True),
        ),
    ]
