# Generated by Django 3.1.6 on 2021-05-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_submission_final_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_statement',
            field=models.CharField(max_length=500),
        ),
    ]
