# Generated by Django 3.1.6 on 2021-06-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20210530_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='solution',
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_statement',
            field=models.CharField(max_length=750),
        ),
    ]
