# Generated by Django 3.1.6 on 2021-06-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_userage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_18_plus',
            field=models.BooleanField(default=False),
        ),
    ]
